name: "CI"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm ci
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use ingageco/setup-ionic
      uses: ./
    - name: Run ionic project tests
      run: |
        ionic start testapp blank --capacitor --type angular --no-link --no-git --no-interactive --confirm
        cd testapp